#%RAML 1.0 NamedExample
value:
 
 -
    ID: 1 
    name: Ron
    contactNo: +1-22-600-3344
    address: Newyork
    status: Active
    dateCreated: 2020-03-18
	
 -
    ID: 2 
    name: Jay
    contactNo: +91- 9971879109
    address: India
    status: Active
    dateCreated: 2020-03-18
	